import type {
    GalleryCategoryOption,
    GalleryProject,
} from './GalleryBasePanelTypes';

export const GalleryCategories: GalleryCategoryOption[] = [
    {
        Id: 'architecture',
        Label: 'Architecture',
        Number: '01',
        Direction: 'top',
    },
    {
        Id: 'journeys',
        Label: 'Journeys',
        Number: '02',
        Direction: 'right',
    },
    {
        Id: 'journal',
        Label: 'Journal',
        Number: '03',
        Direction: 'bottom',
    },
    {
        Id: 'portraits',
        Label: 'Portraits',
        Number: '04',
        Direction: 'left',
    },
];

export const GalleryProjects: GalleryProject[] = [
    {
        Id: 'thresholds-of-light',
        Category: 'architecture',
        CategoryLabel: 'Architecture',
        Title: 'Thresholds of Light',
        Location: 'Lisbon, Portugal',
        Year: '2025',
        ImagePath: '/images/architecture-01.webp',
        Alt: '강한 빛과 그림자가 교차하는 콘크리트 건축 공간',
        Orientation: 'portrait',
        Note: '빛이 구조를 지나며 잠깐의 방이 되는 순간.',
        CreditName: 'Edgar',
        CreditUrl:
            'https://unsplash.com/photos/modern-architecture-with-strong-shadows-and-geometric-patterns-D65d_X1st-c',
    },
    {
        Id: 'concrete-silence',
        Category: 'architecture',
        CategoryLabel: 'Architecture',
        Title: 'Concrete Silence',
        Location: 'Basel, Switzerland',
        Year: '2024',
        ImagePath: '/images/architecture-02.webp',
        Alt: '흑백의 기하학적 콘크리트 벽과 깊은 그림자',
        Orientation: 'portrait',
        Note: '재료가 가장 적은 말로 공간을 설명하는 방식.',
        CreditName: 'Pascal Meier',
        CreditUrl:
            'https://unsplash.com/photos/white-and-black-concrete-building-WotyTSGl91k',
    },
    {
        Id: 'red-mile',
        Category: 'journeys',
        CategoryLabel: 'Journeys',
        Title: 'The Red Mile',
        Location: 'Nevada, USA',
        Year: '2023',
        ImagePath: '/images/journey-01.webp',
        Alt: '붉은 협곡 사이로 길게 이어진 도로',
        Orientation: 'portrait',
        Note: '목적지보다 오래 남은 길 위의 온도.',
        CreditName: 'Dino Reichmuth',
        CreditUrl: 'https://unsplash.com/photos/A5rCN8626Ck',
    },
    {
        Id: 'morning-lake',
        Category: 'journeys',
        CategoryLabel: 'Journeys',
        Title: 'Morning, Still',
        Location: 'Braies, Italy',
        Year: '2024',
        ImagePath: '/images/journey-02.webp',
        Alt: '산과 숲이 잔잔한 호수에 비치는 이른 아침 풍경',
        Orientation: 'landscape',
        Note: '아무 일도 일어나지 않아 완벽했던 아침.',
        CreditName: 'Luca Bravo',
        CreditUrl: 'https://unsplash.com/photos/ny6qxqv_m04',
    },
    {
        Id: 'quiet-gaze',
        Category: 'portraits',
        CategoryLabel: 'Portraits',
        Title: 'Quiet Gaze',
        Location: 'New York, USA',
        Year: '2022',
        ImagePath: '/images/portrait-01.webp',
        Alt: '검은 배경 앞에서 카메라를 바라보는 남성 인물',
        Orientation: 'portrait',
        Note: '표정과 표정 사이, 가장 작은 움직임을 기다린다.',
        CreditName: 'Christopher Campbell',
        CreditUrl: 'https://unsplash.com/photos/rDEOVtE7vOs',
    },
    {
        Id: 'blue-hour',
        Category: 'portraits',
        CategoryLabel: 'Portraits',
        Title: 'Blue Hour',
        Location: 'Studio 07',
        Year: '2025',
        ImagePath: '/images/portrait-02.webp',
        Alt: '푸른 조명 아래 정면을 바라보는 여성 인물',
        Orientation: 'portrait',
        Note: '색이 인물의 또 다른 목소리가 되는 시간.',
        CreditName: 'Chandri Anggara',
        CreditUrl: 'https://unsplash.com/photos/7fF0iei80AQ',
    },
    {
        Id: 'shared-table',
        Category: 'journal',
        CategoryLabel: 'Journal',
        Title: 'Shared Table',
        Location: 'Seoul, Korea',
        Year: '2025',
        ImagePath: '/images/journal-01.webp',
        Alt: '세 사람이 함께 커피 잔을 맞대는 장면',
        Orientation: 'landscape',
        Note: '일상의 기록은 대개 한 잔의 온기에서 시작된다.',
        CreditName: 'Nathan Dumlao',
        CreditUrl: 'https://unsplash.com/photos/6VhPY27jdps',
    },
    {
        Id: 'summer-plate',
        Category: 'journal',
        CategoryLabel: 'Journal',
        Title: 'Summer Plate',
        Location: 'Home',
        Year: '2024',
        ImagePath: '/images/journal-02.webp',
        Alt: '밝은 식탁 위에 놓인 채소와 연어 요리',
        Orientation: 'landscape',
        Note: '계절을 기억하는 가장 직접적인 방법.',
        CreditName: 'Ella Olsson',
        CreditUrl: 'https://unsplash.com/photos/KPDbRyFOTnE',
    },
];
